### ISSUE TITLE
.gitignoreについて

### ISSUE THREAD

**Issue by ttak0422** [kugimasa/unityStudy#18]
プロジェクト作る段階で，使う大枠の技術が決まっていればここで選択しておくと幸せになれるよ
<img width="560" alt="screen shot 2019-03-07 at 1 09 39" src="https://user-images.githubusercontent.com/15827817/53895989-88fb4d00-4076-11e9-9646-e58fb49905f5.png">
どんな奴を書いておけばいいかは[github/gitignore](https://github.com/github/gitignore)を参考にするとよさげ．

途中で追加するのも面倒なので今後の参考までにー．

**Comment by kugimasa** [comment]
ありがとうございます！！！
今Issueに気づきました:sob:
